### ISSUE TITLE
webdav-api: "upload" files 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.nextcloud#15]
e.g. template budget file for each partner or updates "summary" files by the R script. In the later case old files need to be overwritten (problem?)

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#uploading-files

**Comment by hsonne** [comment]
See `?kwb.nextcloud::upload_file()`

Overwriting is not a problem. Take care! For an example see 
https://github.com/KWB-R/kwb.nextcloud/blob/dev/R/.test_put-delete.R
