### ISSUE TITLE
Add tests (running on travis-ci and appveyor) 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.nextcloud#22]
Already set dummy user on cloud and defined environment variables on travis-ci (see https://github.com/KWB-R/kwb.nextcloud/pull/20#issuecomment-638464811). 

Also run [kwb.test::create_test_files()](https://kwb-r.github.io/kwb.test/dev/reference/create_test_files.html) (https://github.com/KWB-R/kwb.nextcloud/commit/3f9a33fb44f965c0957b58945c839435393fae14) but unfortunately wrongly already on "dev" branch. Sorry for that @hsonne

**Comment by mrustl** [comment]
Currently 4 checks fail on travis-ci (see https://travis-ci.org/github/KWB-R/kwb.nextcloud/jobs/694428205#L1224): 

```
> test_check("kwb.nextcloud")

── 1. Failure: dav_path() works (@test-function-dav_path.R#10)  ────────────────

`kwb.nextcloud:::dav_path()` did not throw an error.

── 2. Failure: fileid_to_version_href() works (@test-function-fileid_to_version_

`kwb.nextcloud:::fileid_to_version_href()` did not throw an error.

── 3. Failure: get_property_info() works (@test-function-get_property_info.R#10)

`kwb.nextcloud:::get_property_info()` did not throw an error.

── 4. Failure: path_to_file_href() works (@test-function-path_to_file_href.R#10)

`kwb.nextcloud:::path_to_file_href()` did not throw an error.

══ testthat results  ═══════════════════════════════════════════════════════════

[ OK: 29 | SKIPPED: 10 | WARNINGS: 0 | FAILED: 4 ]

1. Failure: dav_path() works (@test-function-dav_path.R#10) 

2. Failure: fileid_to_version_href() works (@test-function-fileid_to_version_href.R#10) 

3. Failure: get_property_info() works (@test-function-get_property_info.R#10) 

4. Failure: path_to_file_href() works (@test-function-path_to_file_href.R#10) 
```

**Comment by hsonne** [comment]
When you created the tests, calling some functions failed because they need the environment variables that are not set on your computer, I assume. However, in Travis they are set, that's why the functions do not throw an error any more.

**Comment by mrustl** [comment]
Well the output above was the travis-ci log: 
 https://travis-ci.org/github/KWB-R/kwb.nextcloud/jobs/694428205#L1224

**Comment by mrustl** [comment]
Have you added envars for appveyor? Didn`t think about that

![grafik](https://user-images.githubusercontent.com/11964451/83698100-e2975200-a600-11ea-9241-554aa23b3aa4.png)

**Comment by hsonne** [comment]
Of course, now it passed!

**Comment by mrustl** [comment]
For pull requests we need another fix: 
https://help.appveyor.com/discussions/questions/46970-unable-to-access-secure-environment-variable-in-pull-request 

Should be fixed now for this repo !
![grafik](https://user-images.githubusercontent.com/11964451/83698999-36a33600-a603-11ea-8c84-fe11f7fe2b24.png)
